/// @file glm/ext.hpp
///
/// @ref core (Dependence)

#include <glm/detail/setup.hpp>

#pragma once

#include "glm.hpp"

#include "./ext/matrix_double1x1.hpp"
#include "./ext/matrix_double1x1_precision.hpp"
#include "./ext/matrix_double1x2.hpp"
#include "./ext/matrix_double1x2_precision.hpp"
#include "./ext/matrix_double1x3.hpp"
#include "./ext/matrix_double1x3_precision.hpp"
#include "./ext/matrix_double1x4.hpp"
#include "./ext/matrix_double1x4_precision.hpp"
#include "./ext/matrix_double2x1.hpp"
#include "./ext/matrix_double2x1_precision.hpp"
#include "./ext/matrix_double3x1.hpp"
#include "./ext/matrix_double3x1_precision.hpp"
#include "./ext/matrix_double4x1.hpp"
#include "./ext/matrix_double4x1_precision.hpp"

#include "./ext/matrix_float1x1.hpp"
#include "./ext/matrix_float1x1_precision.hpp"
#include "./ext/matrix_float1x2.hpp"
#include "./ext/matrix_float1x2_precision.hpp"
#include "./ext/matrix_float1x3.hpp"
#include "./ext/matrix_float1x3_precision.hpp"
#include "./ext/matrix_float1x4.hpp"
#include "./ext/matrix_float1x4_precision.hpp"
#include "./ext/matrix_float2x1.hpp"
#include "./ext/matrix_float2x1_precision.hpp"
#include "./ext/matrix_float3x1.hpp"
#include "./ext/matrix_float3x1_precision.hpp"
#include "./ext/matrix_float4x1.hpp"
#include "./ext/matrix_float4x1_precision.hpp"

#include "./ext/matrix_int1x1.hpp"
#include "./ext/matrix_int1x1_sized.hpp"
#include "./ext/matrix_int1x2.hpp"
#include "./ext/matrix_int1x2_sized.hpp"
#include "./ext/matrix_int1x3.hpp"
#include "./ext/matrix_int1x3_sized.hpp"
#include "./ext/matrix_int1x4.hpp"
#include "./ext/matrix_int1x4_sized.hpp"
#include "./ext/matrix_int2x1.hpp"
#include "./ext/matrix_int2x1_sized.hpp"
#include "./ext/matrix_int3x1.hpp"
#include "./ext/matrix_int3x1_sized.hpp"
#include "./ext/matrix_int4x1.hpp"
#include "./ext/matrix_int4x1_sized.hpp"

#include "./ext/matrix_uint1x1.hpp"
#include "./ext/matrix_uint1x1_sized.hpp"
#include "./ext/matrix_uint1x2.hpp"
#include "./ext/matrix_uint1x2_sized.hpp"
#include "./ext/matrix_uint1x3.hpp"
#include "./ext/matrix_uint1x3_sized.hpp"
#include "./ext/matrix_uint1x4.hpp"
#include "./ext/matrix_uint1x4_sized.hpp"
#include "./ext/matrix_uint2x1.hpp"
#include "./ext/matrix_uint2x1_sized.hpp"
#include "./ext/matrix_uint3x1.hpp"
#include "./ext/matrix_uint3x1_sized.hpp"
#include "./ext/matrix_uint4x1.hpp"
#include "./ext/matrix_uint4x1_sized.hpp"
